# (PART\*) Part I Theories and Framework {-} 

# Introduction {#intro}

In the past decades, efforts have been made to reduce Automobile Dependency in both developed and developing counties. Many research have found that moderating the car use have positive social, economic and environmental impacts. The negative externalities of automobile include, but are not limited to, congestion, collision, unhealthy lifestyle, urban sprawl, social segmentation, pollution, and Greenhouse Gas (GHG) emission.

Three dimensions can reflect the degree of car use, travel mode, driving frequency, and driving distance.
Previous studies commonly choose two metrics for measuring them, the proportion of auto trips (or other modes) and Vehicle Miles Traveled (VMT) ^[or Vehicle Kilometers Traveled (VKT)].

The proportion of mode is calculated by dividing the number of chosen mode over the total number of trips.
The main travel modes, transit, bicycle, and walking are the alternatives to driving personal car.
Given the same amount of travel demand, more active and transit modes means less car use.
VMT is used to measure the travel distance made by a private vehicle.
An integrated viewpoint is to treat the non-auto trips as zero-VMT.
In this way, the probability distribution of VMT can comprehensively represents the travel behavior. 


The smallest unit of VMT is recorded by trip from a daily travel survey. Then these records can be aggregated to personal or household daily VMT (DVMT).
A traveler's or household's DVMT can account for the degree of automobile dependency by combining the number of trips and driving distance during a day.
Given the survey day is randomly selected, DVMT can reflect the typical travel pattern in general.

Although, there are other approaches collect weekly, monthly, or longer VMT records by tracking car usage.
The odometer records are more likely to represent the usage of vehicle rather than traveler's behavior.
It is not easy to acquire long-term VMT through survey-based method. The annual mileage and fuel efficiency information provided in some public data usually are estimated values using daily records and are not as accurate as DVMT.

On a personal scale, VMT relates to the economic cost of travel by car, while another dimension, travel time measuring the time cost of vehicle travel.
For society as a whole, the total VMT measures the usage of road network. 
Thus, it acts as a major interest within the field of transportation, especially in the research of travel demand and infrastructure capacity. 
And VMT highly correlated with the amount of fuel consumption, which is one of the main indicators of pollution and GHG emission. It is also one of the priority issues involving sustainable development and climate change.

Previous research found that reducing VMT is instrumental in solving some urban problems and improving the qualities of urban life.
It is natural that urban studies try to figure out the relationship between VMT and some urban built-environment factors. Then urban or regional policies could identify the best practices to contribute VMT reduction.






