--- 
title: "The Association Between Travel and Urban Form"
subtitle: "Part II Second field: Statistical Methods"
author: "Shen Qu"
date: "`r Sys.Date()`"
# site: bookdown::bookdown_site
output: 
  # bookdown::gitbook: 
  #   lib_dir: "book_assets"
  #   includes:
  #     after_body: disqus.html
  bookdown::pdf_book:
    toc: true
    toc_depth: 4
  citation_package: biblatex

documentclass: article #ElegantPaper # memoir # custom # amsbook  # scrbook # book
bibliography: [fieldpaper1114.bib, unsorted.bib] #, book.bib, packages.bib
biblio-style: apalike
link-citations: yes
# github-repo: qushen26/field_paper
description: "This is a field paper using the bookdown package."
# abstract: |
always_allow_html: true
fontsize: 12pt
geometry: margin=1.25in
# classoption: openany # remove blank pages
keywords: travel behavior, urban form, regression analysis
header-includes:
   - \usepackage{amssymb}
   - \usepackage{amsmath}
   - \usepackage{fancyhdr}
   - \pagestyle{fancy}
   - \setlength{\headheight}{15pt}
   # - \fancyhead[CO]{\thesection}
   # - \fancyhead[CE]{\thesection}
   # - \fancyfoot[CO,CE]{\thesection}
   # - \fancyfoot[LE,RO]{\thepage}
   # - \fancyhf{}
   # - \rhead{\thechapter}
   # - \chead{Field Paper}
   # - \lhead{\thesection}
   # - \rfoot{Page \thepage}
   # - \usepackage{setspace}\doublespacing
   - \usepackage{subfig}
   - \usepackage{multicol}
   - \usepackage{multirow}


---



```{r setup, include=FALSE}
# knitr::opts_chunk$set(
#   tidy=FALSE,     # display code as typed
#   size="small")   # slightly smaller font for code
# devtools::install_github('rich-iannone/DiagrammeR')
# remotes::update_packages(c("DiagrammeR", "tinytex", "rmarkdown", "knitr"))
# remotes::install_github('rstudio/rmarkdown')
library(pacman)
p_load(tidyverse,kableExtra ,mosaic,ggpubr,factoextra, DiagrammeR,magrittr) #
# if (!require("webshot")) {install.packages("webshot")}
# webshot::install_phantomjs()
knitr::opts_knit$set(root.dir = "C:/E/PhD/courses/Field paper")
knitr::opts_chunk$set(eval=T,echo=F, message=F, warning=F,cache=T,fig.align = 'center') #,fig.pos="!h",fig.dim = c(8, 6)
```


```{r eval=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
bookdown::render_book("index2.Rmd", bookdown::pdf_book(keep_tex = TRUE))
# bookdown::render_book("index.Rmd", bookdown::word_document2())
# bookdown::render_book()
# bookdown::publish_book(account="qushen")
```


```{r include=FALSE,eval=F}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


