--- 
title: "Travel Behavior and Urban Land Use"
author: 
- Shen Qu^["Portland State University, Toulan School of Urban Studies and Planning"]
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook: 
    lib_dir: "book_assets"
  bookdown::pdf_book:
    toc: true
    toc_depth: 4
  citation_package: biblatex
documentclass: book
bibliography: [fieldpaper.bib, book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: qushen26/field_paper
description: "This is a field paper using the bookdown package. The output format for this example is bookdown::gitbook."
abstract: |
  Part I reviews the literature of theories and studies in Travel Behavor and Built Environment.
  
  Daily Driving Distance as the variable of interest, is associated with many factors including Built-Environment variables. Population Density may have more potential to explain the driving distance than people ever thought about.
  
  Part II iintroduces the linear/non-linear models and meta-analysis methods applied on this topic.
  
keywords: travel behavior, urban land use, probability distribution
header-includes:
   - \usepackage{amssymb}
   - \usepackage{amsmath}
   - \usepackage{fancyhdr}
   - \pagestyle{fancy}
   # - \fancyhead[CO,CE]{\thesection}
   # - \fancyfoot[CO,CE]{\thesection}
   # - \fancyfoot[LE,RO]{\thepage}
   # - \fancyhf{}
   # - \rhead{\thechapter}
   # - \chead{Field Paper}
   # - \lhead{\thesection}
   # - \rfoot{Page \thepage}
   - \usepackage{setspace}\doublespacing
   - \usepackage{subfig}
   - \usepackage{multicol}
   - \usepackage{multirow}


---

# Preface {-}

This is a field paper using the **bookdown** package [@R-bookdown], **knitr** [@xie2015] and TinyTeX: <https://yihui.name/tinytex/>.


```{r setup, include=FALSE}
# knitr::opts_chunk$set(
#   tidy=FALSE,     # display code as typed
#   size="small")   # slightly smaller font for code
# devtools::install_github('rich-iannone/DiagrammeR')
# remotes::update_packages(c("DiagrammeR", "tinytex", "rmarkdown", "knitr"))
# remotes::install_github('rstudio/rmarkdown')
library(pacman)
p_load(tidyverse,kableExtra ,mosaic,ggpubr,factoextra, DiagrammeR,magrittr) #
# if (!require("webshot")) {install.packages("webshot")}
# webshot::install_phantomjs()

knitr::opts_chunk$set(eval=F,echo=F, message=F, warning=F,cache=T,fig.dim = c(8, 6),fig.align = 'center') #,fig.pos="!h"
```


```{r eval=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
bookdown::publish_book(account="")
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


