# Travel as Response {#travel}

Disaggregate and aggregate analysis also reflect two different perspectives, individual travel choice or collective human mobility. When researchers observe travel as a personal choice or decision-making, a traveler is a subject to make choices. Some economic and psychological theories are developed to explain why and how a person decides to drive, such as utility-maximization theory. When researchers contextualize the many trips as a whole into the city/region's environment, the human mobility or travel pattern is a social and geographic phenomenon. Some geographic or physical theories express the mechanism behind the pattern, such as the gravity model.

## Travel Variables

Two primary dimensions can measure travel behavior: travel mode choice and degree of car use. Their smallest unit is a trip recorded in the travel survey. When the traveler has decided to have a trip, the chosen mode for each trip, driving, transit, bicycle, or walking, is a discrete variable in the disaggregate analysis. Given a driving trip, the driving distance or driving duration measures the car use intensity, such as Vehicle Miles Traveled (VMT). That means a usage variable is based on a given condition in the mode-choice dimension.

Then, the essential measurements can be converted to other variables. For example, the daily driving frequency is the count number of all driving trips on the survey day. Daily VMT (DVMT) is the total driving distance on the survey day. A travel survey often records the trips with the information of persons, vehicles, and households on the survey day. The trip's VMT and frequency have the corresponding measurements by person, vehicle, or household. Since the internal difference inside a household usually is not the research interest, DVMT per household is generally chosen to reflect the typical travel behavior [@bhatCopulabasedApproachAccommodate2009]. And the household travel records are still treated as disaggregated data. An integrated viewpoint treats the non-auto trips and no-trip as zero-VMT [@ewingVaryingInfluencesBuilt2015]. In this way, the VMT variable can comprehensively represent the overall travel behavior. But researchers should reconsider the VMT's probability distribution.

If the sampling can represent the population's features, these records are further aggregated by a given temporal or spatial unit in aggregate analysis. For a given geographic unit, such as Census Block Group, Tract, or county, the common measures are the averages of the records at the lower scales. Another measure is the mode share or split calculated by dividing the driving frequency over the total number of trips. The share of alternative travel modes has a deterministic relationship to the share of driving. It is not easy to acquire long-term travel information through a survey-based method. Although the survey day may be randomly selected, it is risky to use daily observations to represent monthly or annual features. The annual mileage and fuel efficiency information provided in some public data usually are estimated values using daily records and are not as accurate as DVMT. Tracking car usage such as odometer records can collect weekly, monthly, or longer VMT records [@plotzDistributionIndividualDaily2017]. But this approach is more likely to measure the use of the vehicle rather than the traveler's behavior.

Travel variables relate to social, economic, and environmental meanings in the theories and practices. On an individual/household scale, VMT relates to the financial cost of travel by car. The proportion of transportation cost in household expenditures is about 15 to 25 percent in the U.S. Previous research found that reducing VMT is instrumental in solving some urban problems and improving the quality of urban life. For society as a whole, the total VMT estimates the usage of the road network. Thus, it is a major interest in transportation, especially in researching travel demand and infrastructure capacity. Transportation is the second source of GHG emissions [@hankeyImpactsUrbanForm2010]. VMT is highly correlated with the amount of fuel consumption, which is one of the leading indicators of pollution and GHG emission, further involving sustainable development and climate change. Another measure of car use, driving duration/time, measures travel's time cost connecting to peak hours and congestion. Total driving time is also a good variable reflecting the CO$_2$ emissions and pollution [@gimAnalyzingCitylevelEffects2021].

## Traveler Choice

Are 'decision' and 'choice' the same when discussing travel modes? A 'choice' is one decision given all available options simultaneously. At the same time, 'decision' is a broader concept. A decision could be a schedule with a combination of many choices, such as modes, destination, and activities. A decision related to travel behavior could even include bicycle or car purchase and relocation. This section will start from the theories of mode choice, then extend to a broader discussion of decision processes.

-   Rational Choice Theory

Rationality is a basic assumption in reasoned behavior or rational choice theories for prescriptive, analytical everyday decision-making [@edwardsTheoryDecisionMaking1954; @vonneumannTheoryGamesEconomic1944]. This category is also called 'normative decision theory,' which assumes people a traveler is an ideal decision-maker who is entirely rational. It requires three steps: information collection, utility evaluation, and choice making.

Traditional economics focuses on utility evaluation and comes up with the **Expected Utility Theory** (EUT), also called consumer choice theory. The rule of EUT is **Random Utility Maximization** (RUM) [@ben-akivaDiscreteChoiceAnalysis1985; @mcfaddenConditionalLogitAnalysis1973]. This classical theory claims that customers always choose the most appropriate by comparing the advantages and disadvantages of a range of alternatives, evaluating the benefits and costs of each possible outcome. Eventually, travelers will select the optimal solution with the maximum 'utility' from the choice set.

Expected utility theory is widespread and contributes to economics and other fields. But it has some drawbacks to describing actual human behavior in real life. The observed behaviors are often not optimal and inconsistent with 'pure' rationality. @starmerDevelopmentsNonexpectedUtility2000 explains that EUT is based on three axioms: ordering, continuity, and independence. The choices under risk have non-expected utilities, and the independence axiom is violated. @kahnemanProspectTheoryAnalysis1979a develop the **Prospect Theory** as an alternative to EUT. The real-life individual choice usually is not one-stage but includes at least two steps: editing and evaluation. In the first step of editing, a traveler uses the *satisfying heuristic rule* to make a simple choice. In the second evaluation step, the traveler values the prospect by both values and weights. @tverskyAdvancesProspectTheory1992 further extend this theory to the cumulative prospect theory (CPT). Prospect theory is a descriptive theory with three main features: First, people are more sensitive to the sure things (e.g., the probability between 0.9 and 1.0, or between 0.0 and 0.1 ), while indifferent to the middle range (e.g., from 0.45 to 0.55). Second, people care more about the change of overall proportion than the absolute values regardless of gains or losses. Third, people make choices based on a reference point rather than the general situation or worth. Economists also extend the theory of expected utility maximization to Behavioral Economics by addressing the influence of psychology on human behavior. Travel studies still have no consensus over the utilities' reference points.

**Regret Theory** introduces the notions of risk or uncertainty in decisions [@loomesRegretTheoryAlternative1982]. Psychological studies found that individuals will try to maximize the utility and minimize the anticipation of regret. The fear of regret could affect people's rational behavior. People treat potential gains and losses differently, called Loss Aversion. Loss Aversion suggests that the negative feeling about losses is greater than the positive response about gains [@tverskyAdvancesProspectTheory1992]. As a result, an individual's decisions may not be consistent with the evidence and tend to pay additional costs to avoid losses. For example, A high risk of congestion in peak hours could encourage a commuter to choose rail transit. Likewise, a good reputation for punctuality can give travelers confidence in the rail system. In addition to the traditional utility framework, a regret term is added to address the uncertainty resolution. The utility function on the best alternative outcome will be more minor after subtracting the regret term, an increasing, continuous and non-negative function. Prospect and regret theories provide more realistic explanatory frameworks to account for the limited information and uncertain time of daily travel choice. But they are still not as simple and tractable as EUT and require further study.

The above theories are based on the *weighted additive rule* and represent a *high accuracy-high effort* mechanism [@ramosStateoftheArtReviewDevelopments2014]. But individuals often do not collect and analyze all the relevant information. The decision-makers are not 'ideal' and cannot calculate the utility for all possible alternatives with perfect accuracy. In terms of travel behavior, the accurate evaluation of each trip seems unnecessary and impossible for the regular daily activity. In many cases, travel decisions are not the best way to achieve travelers' desired objectives. A psychological factor, **cognitive bias**, can result in judgment errors. For example, transit users value the walk and wait time called out-of-vehicle time (OVT) higher than in-vehicle time (IVT). Drivers place more value on car parking space search time [@wardmanValuesTravelTime2016]. Some theories of **Bounded Rational Behavior** were developed to fix these issues. Bounded rationality focused on the limitation of self-control [@marchCognitiveLimitsRationality2005]. In reality, individuals behave under many constraints, including incomplete information, limited time, and cognitive capacity.

Bounded rationality claims that heuristics and rules of thumb are more common than comprehensive evaluation when people make decisions under constraints. People are satisfied with a 'good enough' decision unless there is a definitively better alternative. The recently witnessed events would have more potent effects on an individual's decision than others [@camererAdvancesBehavioralEconomics2004].

-   Theory of Planned Behavior

A person as a subject does not merely execute the order from a utility evaluation and do "what he/she wants to do." Many theories and models are developed to explain people's decision-making processes in psychology [^travel-1]. Theory of Planned Behavior (TPB) is one of the most influential theories. @ajzenAttitudebehaviorRelationsTheoretical1977 proposed the theory of reasoned action (TRA) to understand people's *behavioral intentions* and actual behaviors. They found two deciding psychological elements as *attitudes* and *subjective norms*. @ajzenTheoryPlannedBehavior1991 adds a new part of *perceived behavioral control* (PBC) and renames TRA as TPB.

[^travel-1]: CMDT=Cognitive moral development theory (Kohlberg, 1984),

    ITB=Ipsative theory of behavior (Frey, 1988),

    NAM=Norm activation model (Schwartz, 1977,Schwartz and Howard, 1981),

    SDT=Self-determination theory(Deci & Ryan, 1985),

    TAM=Technology acceptance model(Davis, 1989),

    TDM=Travel demand management measures,

    TNC=Theory of normative conduct (Cialdini et al., 1990,Cialdini et al., 1991),

    TPB=Theory of planned behavior(Ajzen, 1985,Ajzen, 1991),

    VBN=Value-belief-norm (Stern, 2000,Stern et al., 1999),

    MGB=Model of goal-directed behavior(Perugini & Bagozzi, 2001)

Attitudes are personal evaluation, and it means how people prefer or are against performing an activity. For example, a commuter might choose transit despite the longer travel time than driving because this person believes that transit is an environment-friendly transport mode. Subjective norm is the social pressure from others. In the example above, choosing transit is because of other people's normative expectations rather than personal desirability. PBC represents some non-volitional factors such as time, budget, and resources. PBC is assessed by the individual's perception of ease or difficulty of the behavior. PBC is one reason for the difference between intentions and actual behaviors, called the attitude-behavior gap [@kollmussMindGapWhy2002; @laneAdoptionCleanerVehicles2007]. In this case, a commuter might choose transit because this person is confident in catching the morning bus every day.

Based on RUM models, @mcfaddenEconomicChoices2001 proposes a similar framework called the choice process, including attitudes, perception, and preference. This framework is further developed to hybrid choice model (HCM) and non-RUM decision protocols [@ben-akivaHybridChoiceModels2002].

Two meta-analyses found that intentions to drive, perceived behavioral control, habits, and past behavior play the primary roles in travel mode choice [@lanziniSheddingLightPsychological2017; @gardnerPsychologicalCorrelatesCar2008]. Among these factors, PBC has the most potent effects on private car use. People don't want to reduce car use because they think it is very inconvenient. The impact of attitudes is modest, while subjective norms have a weak effect on car use. @dillHowCanPsychological2014 confirm that social norms have no significant impact on walking and bicycling. They find attitudes have a stronger connection to bicycling while PBC is more important for walking. Their study also reveals that some built-environment factors could impact attitudes and PBC, further influencing cycling and walking behavior. That means attitudes and PBC are mediators for the relationship between travel and urban form. By controlling the mediators in the models, the correlation between travel and urban form should be stronger.

## Human Mobility

In physics and geography, travel activities and papatternsre are considered objective phenomena and conventionally called human mobility. There is a long history of human mobility studies. The related theories use mathematical expressions to explain the relationship between ob travel variables and the influencing factors. Gravity Law is a primary theory in this field. Scholars have developed some more delicate forms of gravity model and found some mathematical relationship to other famous distribution laws. Some theories from different perspectives, like intervening opportunities, also show a vital ability for explaining travel patterns and regularities.

-   Distance-Based Theories

An early theory called **Law of Migration** by @ravensteinLawsMigration1885 tried to explain the regional migration patterns. This foundation is based on observation rather than quantitative analysis. But it captures the fact that the direction of migration is toward the regional center with grand commerce and industry. It also pointed out that distance is a primary factor for migrants. This theory inspired many studies on population movement consequently. Even today, socio-economic factors and distance constraints are the essential parts of the relevant models and frameworks.

**Zip's law** is also called discrete Pareto distribution. It is found in linguistics to explain the inverse relationship between the frequency and rank of a word. The charm is that this rank-frequency distribution disclosed a universal law in many realms of society and physics, such as urban size, corporation sizes, cells' transcriptomes and so on. Zipf interpreted the two competing factors as *force of diversification and unification*. The former produces larger amount of cases and the later tries to upgrade the rank. An equilibrium of the rank-frequency balance is controlled through a parameter $\alpha$ in the exponent. For example, a city's population size $m$ has a negative power relationship to its rank $r$. [@visserZipfLawPower2013; @jiangZipfLawAll2015; @rozenfeldAreaPopulationCities2011; @gomez-lievanoStatisticsUrbanScaling2012; @hackmannEvolutionZipfLaw2020]

@zipfP1P2Hypothesis1946 extended his theory to describe the traffic in both directions between two cities. The traffic flow of goods between two centers is proportion to the product of two centers' population sizes divided by the distance between them. Because Zipf's formula has a same form with Newtonian mechanics [@newton18481687], people call this expression as **Gravity Law**. <!-- $$m \sim 1 / r^{\alpha}$$  -->

<!-- $$t_{ij}\propto \frac{m_i m_j} {d_{ij}}$$ -->

<!-- where $t_{ij}$ represent the traffic flow of goods between two centers $i$ and $j$ with population sizes $m_i$ and $m_j$. $d_{ij}$ is the distance from $i$ to $j$.  -->

<!-- As the most influential theory, Gravity Law asserts that the amount of traffic flow between two centers is proportion to the product of their mass and inverse to their distance. The mass is often measured by population size. -->

<!-- \begin{equation} -->

<!-- p_{ij}\propto m_i m_j f(d_{ij}), \qquad i\ne j  -->

<!-- (\#eq:gravity-law) -->

<!-- \end{equation} -->

<!-- where $p_{ij}$ is  $i$ $j$ satisfying $\sum_{i,j=1}^n p_{ij}=1$. $m_i$ and $m_j$ -->

Gravity law has been applied in travel demand modeling for many years. The traditional four-step models include trip generation, trip distribution, mode split, and trip assignment [@ortuzarModellingTransport2011]. As a trip-based method, gravity models generate the Origin-Destination matrix in the step of trip distribution [@mcnallyFourStepModel2008]. All paired units are assigned the estimated traffic flows based on each unit's trip generation and attraction. The probability of commuting between origin and destination is proportion to the population of two units and inverse to their distance. In the version of the single-constrained or unconstrained gravity model, the generation of an origin does not equal the sum of flows to all destinations, or the attraction of a destination does not equal the sum of flows from all origins. Only the doubly constrained gravity models guarantee that the two equations hold.

<!-- with a parameter $\lambda$ showed as below: $d_{ij}$ -->

<!-- $$f(d_{ij})=\exp(-\lambda d_{ij})$$ and -->

<!-- $$f(d_{ij})={d_{ij}}^{-\lambda}$$  -->

Zipf's and gravity laws have a common essence of the power-law or scaling pattern. The Zipfian distribution is one of a family of **power-law** probability distributions. The power-law distribution also holds in many realms: urban size, population density, street blocks, building heights, etc. The state-of-the-art human mobility studies agree that travel behavior follows a power-law distribution at the population level [@barbosaHumanMobilityModels2018]. An example is @brockmannScalingLawsHuman2006 use dollar bills to track travel habits and confirm this theory. It reflects that trip and land use, as two geographic variables, follow some Paretian-like distribution. Apparently, it conflicts with Gaussian thinking, the foundation of linear models based on the location and scale parameters [@jiangZipfLawAll2011; @chenHierarchicalScalingSystems2018; @jiangGeospatialAnalysisRequires2018; @jiangSpatialHeterogeneityScale2018]. Meanwhile, the log-normal distribution may be asymptotically equivalent to a special case of Zipf's law, which could support the logarithm transform in some travel-urban form models [@saichevTheoryZipfLaw2010].

The criticism includes that the four-step model uses TAZ inputs and fails to capture the built environment effect at the neighborhood level [@davidsonSynthesisFirstPractices2007]. @nostikasariRepresentationsEverydayTravel2015 analyze the everyday experience in Dallas-Fort Worth metropolitan area and find the daily travel demands in various population groups are not support the assumptions in four-step models. This institutionalized method may enforce auto dependence and social inequality. Some studies have developed an integrated model in recent years and have gotten consistent results among each step [@zhouAlternativeFormulationsCombined2009].

<!-- In transportation modeling, a common form of gravity model is : -->

<!-- $$T_{ij}= \alpha_i O_i \cdot \beta_j D_j \cdot f(d_{ij})$$ -->

<!-- where $T_{ij}$ is the flow between $i$ and $j$.  -->

<!-- the two population are replaced by total trip generation of origin $O_i$ and total trip attraction of destination $D_i$. $\alpha_i$ and $\beta_j$ are two constraining parameters to satisfy $\sum_{i}^{n_i}T_{ij} = D_j$ and $\sum_{j}^{n_j}T_{ij} = O_i$. It means that $\alpha_i = [\sum_{j}^{n_j} \beta_j D_j \cdot f(d_{ij})]^{-1}$ and $\beta_j = [\sum_{i}^{n_i} \alpha_i O_i \cdot f(d_{ij})]^{-1}$. Thus, this model is called as doubly constrained gravity model. -->

-   Opportunity Based Theories

**Law of Intervening Opportunities** by @stoufferInterveningOpportunitiesTheory1940 developed the migration theory differently. Stouffer proposed that "the number of people going a given distance is directly proportional to the number of opportunities at that distance and inversely proportional to the number of intervening opportunities." The number of intervening opportunities replaces the distance between origin and destination compared with gravity law. That means a resident living in one location and attracted to another site is affected by the number of jobs, public services, and other opportunities between the two places.

<!-- $$p_{ij}\propto m_i \frac{P(1|m_i,m_j,s_{ij})}{\sum_{k=1}^n P(1|m_i,m_j,s_{ij})}, \qquad i\ne j $$ $s_{ij}$ $i$-->

<!-- where the conditional probability $P(1|m_i,m_j,s_{ij})$ can be expressed by Schneider (1959) as: -->

<!-- $$P(1|m_i,m_j,s_{ij})=\exp[-\gamma s_{ij}] - \exp[-\gamma (m_j + s_{ij})]$$ -->

@siminiUniversalModelMobility2012 propose a **radiation model** express the probability of the destination absorbing a person living in one location, which is mutually decided by the population of origin, destination, and the population within a circle centered at origin. The expression can has several forms. One form is that the traffic flow equals the the product of original trips and two weights, the weights of origin and destination in the whole region. Although distance doesn't appear in the expression of radiation model, it is still a determinant as in gravity model.

<!-- $$P(1|m_i,m_j,s_{ij})= \frac{m_i m_j}{(m_i + s_{ij})(m_i + m_j + s_{ij})}$$ $i$ as below:$j$-->

<!-- Or in transportation model it is expressed as: -->

<!-- $$T_{ij}= O_i\cdot\frac{m_i m_j}{(m_i + s_{ij})(m_i + m_j + s_{ij})}$$  -->

<!-- To approximating the number of opportunities, $s_{ij}$ is from the population within a circle centered at origin. The radius is the distance between $i$ and $j$. Then $m_i + m_j + s_{ij}$ represents the total population within the circle, and $m_i + s_{ij}$ is the total population within the circle but excluding $j$, that is: -->

<!-- $$T_{ij}= O_i\cdot\frac{m_i }{m_i + s_{ij}}\cdot\frac{m_j}{m_i + m_j + s_{ij}}$$   $d_{ij}$-->

-   Distance Decay

In geographic studies, the distributions of density, frequency, or intensity from an initial point show a monotonically decreasing curve. This rule of distance decay is widespread and called "the first law of geography" [@toblerComputerMovieSimulating1970]. The distance decay rule reveals that the relationship between trip frequency and travel distance is not linear [@taylorDistanceDecaySpatial1975]. An improved gravity model uses a distance decay function on distance to replace the simple distance. Exponential and power are the two forms of the distance decay functions. Both of them better represent the decaying processes by introducing a new parameter. The parameter controlling decay speed is also called travel impedance in travel demand models. @handyPlanningAccessibilityTheory2005 treats impedance as one component of accessibility. In practice, the parameter values are calibrated using observed trips data.

Traditional opportunity-based cannot reflect the feature of declining along with distance as well as the improved gravity model. Based on commuting data from six countries, @lenormandSystematicComparisonTrip2016 found gravity law performs better than the intervening opportunities law. One reason could be that the circle with a radius can not represent the actual travel distance. Moreover, The intervening-opportunities models may miss some mechanism without accounting for distance decay. @yangLimitsPredictabilityCommuting2014 extend the opportunity-based model by assuming a trip from origin to destination as a time-to-event process called **hazard models**. Under the survival analysis framework, the time variable is replaced by the number of opportunities $a$. The survival function $S(a)=Pr(T>a)$ then represents the cumulative probability of the event not happening within a certain amount of opportunities. Their extended radiation model performs as well as the doubly constrained gravity model in a multi-scale study.

In @dingInfluencesBuiltEnvironment2017 's study, the time variable in the decay function is replaced by commuting distance. Unlike common regression models, they use a Cox proportional hazard model to examine the effects of built-environment factors at the TAZ level and socio-demographic characteristics at the individual level on commuting distance. Using the Washington metropolitan area data, their model confirms that residential density, land use mix, and distance from CBD can significantly impact commuting distance. And their multilevel hazard model outperforms the general multilevel model.

These studies inspire us to rethink the convention of log-transform on travel variables. In regression analysis, log-transform implies that the travel variables, such as trip distance/time, follow the log-normal distribution. @puAnalyticRelationshipsTravel2011 choose log-normal as a prior assumption because the F-SHRP report [^travel-2] says "the log-normal distribution is the closest traditional statistical distribution that describes the distribution of travel times." But the new version of SHRP2 says, "formal tests (e.g., a Kolmogorov-Smirnov test) could be employed to evaluate the assumption and identify the sensitivity of the results to departures from this assumption." (p. 130) That means the assumption of log-normal distribution does not always hold.

[^travel-2]: which can be found in Future Strategic Highway Research Program (SHRP) by @cambridge2003providing and @kittelson2013evaluating

Survival analysis, also called time-to-event analysis, often chooses three distributions in parametric approaches: Weibull, Gamma, and Log-normal distribution [@kleinbaumSurvivalAnalysisSelfLearning2012]. Some studies explore using these distributions to fit the travel data. @linEstimationEnergyUse2012 validates the daily vehicle miles traveled (DVMT) following a gamma distribution in the context of PHEV [^travel-3] energy analysis. Based on the multidate (7-200 days) data sets from four countries, @plotzDistributionIndividualDaily2017 found Weibull distribution is an overall good two-parameter distribution for daily VKT. At the same time, the log-normal estimates are more conservative.

[^travel-3]: Plug-in hybrid electric vehicles

The studies on travel distributions are still not conclusive. But they show a potential relationship among log-transform, distance decay, and travel-time-budget theories [@marchettiAnthropologicalInvariantsTravel1994]. Similarly, @kolblEnergyLawsHuman2003 show a canonical-like energy distribution for short trips by modes, which imply "a law of constant average energy consumption for the physical activity of daily travel." Some studies are not limited to parameter methods. @siminiUniversalModelMobility2012 propose a parameter-free model that predicts patterns of commuting.

<!-- Choosing Weibull distribution as the survival function -->

<!-- , $S(t)=\exp[-\lambda t^\alpha]$ with scale parameter $\lambda \in (0, +\infty)$. By assuming $f(\lambda)=\exp[-\lambda]$ and integral on $\lambda$, the derivation is: -->

<!-- \begin{equation} -->

<!-- (\#eq:sf1) -->

<!-- \begin{split} -->

<!-- P(T>t)=&E\{\exp[-\lambda t^\alpha]\} \\  -->

<!-- =&\int_0^{+\infty}\exp[-\lambda t^\alpha]\exp[-\lambda]d\lambda\\ -->

<!-- =&\frac{1}{1+t^{\alpha}} -->

<!-- \end{split} -->

<!-- \end{equation} -->

<!-- By replacing $t$ with $m_i+s_{ij}$, the conditional probability is: -->

<!-- $$\begin{aligned} -->

<!-- P(1|m_i,m_j,s_{ij})= &\frac{P(T>m_i+s_{ij})-P(T> m_i+s_{ij}+m_j)}{P(T>m_i)} \\  -->

<!-- =&\frac{[(m_i + s_{ij} + m_j)^{\alpha}-(m_i + s_{ij})^{\alpha}](m_i^{\alpha}+1)}{[(m_i + s_{ij} + m_j)^{\alpha}+1][(m_i + s_{ij})^{\alpha}+1]}\\ -->

<!-- \end{aligned}$$ -->

<!-- where $\alpha$ is a parameter adjusting the effect of the number of job opportunities between origins and destinations. $d_{ij}$-->

-   Time Geography

In contrast to overall trip distribution, the detailed individuals' movements are also research interest in geography. @hagerstraandWhatPeopleRegional1970 proposed some concepts and tools in space and time to measure and understand the individual trajectories. This branch is called time geography. The famous "space-time aquarium/prism" is a 3D cube that adds temporal scales to the geographic space. It can capture the detailed structure and behavior of travelers.

The aggregated trips' tempo-spatial distributions are essential for transportation infrastructure. Compared to daily total traffic volume, the maximum flows in peak hours represent the actual demand for the road network. Based on the trips' distributions, planners can identify the most critical segments and relieve congestion by increasing these segments' capacity. For shared mobility, The placement of shared-bicycle stations can be optimized by analyzing the pattern of riders' travel trajectories [@parkOptimizationApproachPlacement2017]. Using the trajectory data in New York City, @qianImpactTransportationNetwork2020 find that transportation network companies (TNCs) services indeed increase the urban traffic congestion.

Time geography can better understand the relationship between travel and urban form. A daily trip could include multiple trips and form a travel chain. The traveler may switch the sequence or adjust the routes to optimize the chain and minimize the travel costs. Given the same daily total travel distance, the travel chain could include a long driving trip or many short trips. The same trip frequency could cross the city with a lot of trouble and could also be a series of leisure activities downtown. @ewingReducingVehicleMiles2020 examine the travel chains in 28 U.S. regions and find that the tours inside the urban centers are more efficient than those outside the centers and hybrid (both inside and outside the centers). That means the tours within a center have shorter VMT per trip and higher shares of walk, bicycle, and transit.

Time geography borrows some physical and mathematical concepts and methods such as random walk, Brownian motion, and Levy flight at the individual level. With the wide usage of Global Positioning System (GPS), high-performance computing, and sophisticated algorithms, high-resolution data is being collected. The relevant studies also have a dramatic increase after 2005. @liuPointofInterestDemandModeling2017 use point-of-interest data to disclose better the distribution of opportunities than merely using population size. Using mobile phone data, @sabouriBuiltEnvironmentVehicle2021 find a new version of scaling law: the number of visitors to one location is proportional to "the inverse square of the product of travel distance and visiting frequency." Their found can also help explain the connection between individual trips and aggregated travel patterns.

<!-- ## Summary (Opt.) -->

<!-- The theories of travel behavior have followed a positivist tradition for a long time. Economics and geography give strong explanations for macro and micro travel patterns. To remove the limitation of ideal rationality, more sociological and psychological theories and methods are introduced into this field. Gradually, people realized the normative concept is not sufficient for real-world applications. More descriptive and narrative arguments appear in transportation and land use planning. An example is a shift from mobility to accessibility. -->

<!-- A primary trend in urban and transportation fields recently is the transition from techno-centric to socio-centric [@lanziniTechnocentrismSociocentrismEvolution2021] The socio-centric methods claim that accessibility is the key concept for evaluating sustainable urban mobility. This trend emphasizes the interpretations of travel behavior are context-dependent and avoid generalizations. -->

<!-- Research in human mobility insists on the positivism methodology and has significant contributions because the individual differences are confounded at the macro level. Under this framework, geographic distance plays a prominent role in all human mobility theories. In adding to travel distance and Origin-Destination Matrices, Some primary metrics such as Mean Square Displacement and Radius of gyration are defined to quantitatively describe travel behaviors -->

<!-- A vital insight is that human behavior has two mobility roles: explorers and returners. It might be an inherent property of society, the instinct to explore more territory and keep together for labor division. The explorers' behavior is consistent with the theory of utility maximization. People are always looking for more benefits. The concept of habit also matches the behavior of 'preferential return' behavior, which means people are natural or nurtured likely to return to frequently visited or recently-visited locations. -->

<!-- Both gravity and opportunities theory choose population size as the source of travel demand. This is a rough assumption and is insufficient to get more accurate predictions. One solution is to use observed empirical demand to calibrate the model case by case. Another way is to find more suitable variables such as residential, employment, or activity size to improve the model. -->

<!-- When the area of interest is intra-urban, the O-D matrix records the trip connections among all paired locations. The matrix contains plenty of information, including urban spatial structure, opportunities, activities, and other socio-economic characteristics. The theories imply that the O-D matrix has some strong connections to travel behavior in some ways. The first challenge is to mine the information and extract some explainable elements. A limitation is that the empirical O-D matrix may only reflect the particular characteristics in that city and can not be applied to others. The second challenge is how to get a generalized interpretation, -->

<!-- Once choosing the individual perspective, current theories and methods are still insufficient. For example, the physical transportation network is only a part of travel decisions. Social networks with a 'hub-and-spoke structure' play a prominent role in finding a job. Some studies provide valuable insight using social media data but still have a gap to form new theories. -->

<!-- An interdisciplinary perspective could provide a theoretical explanation for model selection. Existing mobility theories can play an anchor to identify the key variables' properties and confirm the additive and linear relation among the factors. -->
