# Summary {#summary}


After reviewing these theories and frameworks, we go back to the real-world problems. Imagining a scenario of the public hearing, a bill under consideration is about changing the rule of land use and development (e.g., Oregon legislators passed the first law (HB2001) in the United States legalizing duplexes on city lots in 2019 [^references1-1]). It is widely recognized that less driving means a more healthy, environment-friendly lifestyle. At the hearing, a scholar is asked to provide solid evidence to clarify the relationship between urban form on travel behavior. Combining with the previous introduction, we could think about several questions:

[^references1-1]: <https://www.oregon.gov/lcd/UP/Pages/Housing-Choices.aspx>

The first question is, do travel-urban form studies need causal inference? In natural science studies, causality is often the final goal, such as the relationship between vaccination and contagious. However, observational data would not give the unobserved or counterfactual outcome in social studies. Under a new rule, land use transformation is gradual over several years or even longer. Many factors are changing in the meantime (e.g., real estate market, parking space). Some uncontrollable factors could also shift the outcomes (e.g., pandemic, autonomous vehicles). For some quantitative methods applied in previous studies, such as entropy index and SEM, the calculating parts are objective, but the formulating parts are still subjective. Even in the quasi-experimental design, the judgments remain hypothetical. The conclusions are untestable and unfalsifiable. Compared with causation, the association study looks more conservative but is still valid. Suppose the people inside UGB or TOD areas drive less than outside. In that case, the policies are successful either because original residents change their behavior or new residents move in. Therefore, this paper stays on the studies of association. The primary question is "people living in a similar urban environment have similar travel patterns," rather than "people change their travel behaviors by urban form."

The second question is, are more detailed data and more complicated frameworks more useful? The words 'ecological fallacy' could make people think that the higher resolution and more complex data would give more accurate estimates and be closer to the truth. If the policy-making is interested in the overall pattern, adding the information at the individual level may not help. If planners want to improve the active travel infrastructure like the bike lanes, the individual factors will become critical. Usually, frameworks with more relevant factors and layers have a stronger explanatory ability. But the direct intervention on many influencing factors is impossible (e.g., climate, age, income). Or some interventions have tremendous economic and political costs (e.g., road capacity, fuel price). Therefore, no matter how many factors are involved, a good framework should identify some core factors with precise meanings, definite measures, and operational tools. The multi-layer structures could better represent the actual relations. Since the meaning of one factor could change with the scales, the more complex structure has higher data and assumptions requirements. Meanwhile, a neat design could be more robust and compelling for the public.

The last question is, do we have better ways to estimate the association? Previous studies show the impact of D-variables is weak. Moreover, this conclusion is still controversial in academia. Of course, this result is not compelling in a public hearing. Some synthesized indexes from D-variables show much more potent effects on travel. It implies the answer may still hide inside the D-variables and is waiting to be revealed. Both distance-based and opportunity-based theories inspire us to rethink the relationship between travel and D-variables. Density, mixed land use means more opportunities in the same area. Design (intersection density or proportion of four-way intersections) and distance to transit represent travel impedance or cost. Destination accessibility measures both the impedance and opportunities (e.g., distance to CBD or available jobs within a given travel time). That might be why some studies find destination accessibility has the most decisive influence on travel. Urban transportation is a connected system. The studies merely using travel survey data may have some systematic drawbacks on the destination side.

Finally, the study results should convert to some guidelines and recommended values for practical applications. Each policy has its affecting scope. UGB imposes the radius of urban development. TOD projects change the built environment around the stations. House Bill 2001 releases the restriction on only low-dense communities. It is necessary to clarify the factors' effective range and the meaning. The 4000 and 8000 persons per square miles in statistical models only have a magnitude difference. But in real life, the two density values represent distinct urban areas. They may have their specific features, problems, and visions. We may cluster the urbanized areas into typical categories and find the most sensitive areas. If the association between travel and urban form in these areas is strong, we can know where the compact development works and where it does not work. The threshold analysis may do a similar job. It can help select the strategic focus areas and prioritize planning for limited public resources. For instance, useful results could be like this: In the cities with CBD density below 6000 persons per square miles, the residents who can access an activity center in 10 minutes have a larger share of transit and shorter driving distance.

<!-- -   Goals -->

<!-- trip frequency, traffic mode split, and travel distance are three major dependent variables. The theory of Utility Maximization tells us a trip as an event must have some 'utility' or 'benefit.' Nobody wants to reduce the total number of trips because it reflects the social activity level and is a sign of urban prosperity. People don't object to a sustainable way given a fixed number of trips. More shared trips with shorter distances are desirable. Hence mode split and driving distance are the targets in this field. -->

<!-- TPB and prospect theory could explain people's decisions and choices better. This fact reminds us researchers should not have some high expectations about the role of urban form. Adding the attitude, habit, intention into the models does improve the goodness of fit. Individual travel behavior and social travel pattern might also be different topics. The former studies could be applied to micro design, while the latter is more important for policymaking. -->

<!-- -   Paths -->

<!-- Researchers could choose a suitable analysis framework for their research questions. A multistage framework can be used in longitudinal studies. Collecting the data of residents' relocation, car ownership, and travel behavior can figure out how these variables change with the built environment over many years. This study may have limitations for necessity and sufficiency, but long-term evidence is often more impressive for public opinion. -->

<!-- A tree structure covering all decision nodes could better reveal the whole travel pattern. The trip decision, mode choice, and driving distance make up the travel pattern. Merely looking at one node could be misleading. -->

<!-- A hierarchical framework helps identify one factor's effective scale on travel. It matters because  -->

<!-- All factors related to spatial distributions have morphological attributes. These attributes directly or indirectly affect travel behavior through some functional ways -->

<!-- such as road network connection -->

<!-- such as distance to transit services.  -->

<!-- This perspective helps people figure out the influencing path and better understand the underlying mechanism. -->

<!-- another way of understanding the role of land use is morphology versus functionality.  -->

<!-- the demand or utility of travel is the primary node affecting travel choice.  -->

<!-- The available transportation modes are the secondary nodes that allow travelers to compare and choose among driving and others. Choosing routes and departure time is in the third level. -->

<!-- The travel demand or utility mainly decides the driving distance. The lower levels ' choices could change the driving distance only when the demand is not strong enough or has many alternative destinations. -->

<!-- If one focuses on auto trips. The tree can be simplified to two levels: driving or not. -->

<!-- From the travel behavior perspective, driving distance locates on a terminal node of a trip decision tree. -->

<!-- The tree shows that the first two levels could produce some 'zero' driving distance. Should these cases be included in the studies of driving distance? -->

<!-- This discussion demonstrates a hierarchical relationship among driving distance and other trip variables. -->

<!-- In this way, the transit services are located on the second internal node. -->

<!-- the travel destination may be determined before the decision-making or be selected after the traveler compares several plans. -->

# References {.unnumbered}
