# Summary {#summary}

Part II starts from the first question in modeling, what type of model should we choose? Then the following question is, do this method is correct? The last question would be, how can we do better? Recent literature usually focuses on the third question. But for any research, the first two questions are not self-evident. Thus, this paper makes efforts to review some fundamental knowledge.

For the first question, existing theories have given hints for sorting the travel data and models according to their properties. But in literature, some still contradictory cases need further testing and comparison (e.g., ordinary linear models with log-transform on count data v.s. count data models). Each method has a suitable application and limitations. For example, PCA has become less used in the last three years because it is hard to interpret.

Several common issues are presented to remind the second question. Derivation and test are two ways of proving a statistical method. In the literature, we can only see the author's choices of data and methods. Without replicating the models, it is hard to assess the processes. The real world has no perfect data. Although some diagnosis and validation methods can aid us in finding some problems, the results would not tell us what we should do automatically. The only way is to try many data and methods and repeatedly check the results.

Spatial effects are heeded in recent studies. For heterogeneous issues, GWR and aggregation represent two distinct solutions. GWR captures the local dynamic among the spatial data and requires intensive computation. The aggregated methods try to eliminate heterogeneity. As the sample sizes inside the aggregating areas increase, the variance of estimated coefficients will decrease. "Ecological fallacy" sounds like a mistake. The small scale could also distract the researchers by unimportant details. Relevant aggregated data and models structure should match the research question.

Capturing the nonlinear feathers is also popular in recent studies. From the perspective of policy implementation, the public may only concern about some effective ranges of variables. For example, in rural areas or CBD, population density would not be a helpful tool for intervention. Threshold effects or synergistic effects are also interesting because they can tell planners and policymakers how to select an effective combination from the toolbox. There always are new methods being developed. This paper gives a brief on some advanced techniques such as machine learning. These methods provide additional tools for examining the results and would not replace the traditional way.

<!-- Though this paper, the gain is that now I can identify the category one method belongs to.  -->

<!-- If some methods such as machine learning are required, I can further study this topic.  -->

<!-- Critically discussing the statistical methods in literature is a huge challenge. -->

<!-- Most of the time, I try to understand the methods and mainly focus on the classic approaches. -->

<!-- I often doubt whether my commons are correct or misunderstand the author's meaning or the method itself. -->

<!-- It is necessary to read these cited articles a third time and more. -->

<!-- -   Meta-Analysis in travel-urban form studies -->

The meta-analysis in travel-urban form studies faces more exacting challenges. The same on many social studies, travel-urban form studies use observation design. They cannot satisfy the requirement of randomized controlled trials (RCT). The urban environment factors have many unknown and complex influences on travel behavior. They are not controllable as in the laboratory. All the traveler lives in the various urban environment. There is no control group for measuring the between-group mean difference. Most travel surveys only capture a moment of travel pattern. There is no repeated measurement for evaluating the random error. These shortfalls also make the relevant studies are highly heterogeneous. If the scope of investigations is broad, the validity of meta-analysis becomes problematic. If the selection criteria are rigorous, less than ten studies on a topic might be available.

Although meta-analysis in travel-urban form studies is not as reliable as RCT studies. Scholars still put effort into this approach. Because a generalized conclusion could have a substantial influence on policymaking and social attitudes.

<!-- `r if (knitr:::is_html_output()) ' -->

# References {.unnumbered}
