# (PART\*) Part I Theories and Framework {-} 

# Introduction {#intro}

## Background

In the past decades, efforts have been made to reduce Automobile Dependency in both developed and developing counties. Many research have found that moderating the car use have positive social, economic and environmental impacts. The negative externalities of automobile include, but are not limited to, congestion, collision, unhealthy lifestyle, urban sprawl, social segmentation, pollution, and Greenhouse Gas (GHG) emissions.

In urban planning and transportation, achieving this goal requires two parts. First, researcher find a set of factors which could mostly explain and affect travel behavior. Second, planning and policy are made to intervene the adjustable factors then to reduce the car use significantly.
This paper focuses on the first part and aims at supporting the second part.



## Analytical Framework

Regression Analysis provides a powerful framework for explaining the relationship between urban form and travel.
A large mount of studies use regression models to identify the influencing factors and evaluate the effect size. Previous research demonstrated that there is not a single factor determining travel behavior. When choosing continues response, like Vehicle Miles Traveled (VMT) ^[or Vehicle Kilometers Traveled (VKT)], the basic structure of the regression model is as below:

$$\begin{equation}
\mathbf{Y}=\mathbf{X}\boldsymbol{\beta}+\boldsymbol{\varepsilon}
(\#eq:lm)
\end{equation}$$

where $\mathbf{Y}$ are the variable of VMT. $\mathbf{X}$ are all relevant covariates with corresponding coefficients $\boldsymbol{\beta}$. $\boldsymbol{\varepsilon}$ are a random error terms with expected value of $0$ and variance $\sigma^2$.

When the response is categorical variable, such as binary data of driving versus not, polytomous data of mode choice, or count data of trip frequency, the proper model is:

$$\begin{equation}
E[\mathbf{Y}|\mathbf{X}]=\mu=g^{-1}(\mathbf{X}\boldsymbol{\beta})
(\#eq:glm)
\end{equation}$$

Where $E[\mathbf{Y}|\mathbf{X}]$ is the expected value of individual/household-level travel variable $\mathbf{Y}$ conditional on $\mathbf{X}$; $\mathbf{X}\boldsymbol{\beta}$ is a linear combination (Ditto.); $g(\cdot)$ is a link function.


## Content Organization

<!-- \@ref(struc) -->
As the essential parts of regression analysis, independent variables of [Urban Form](#form) and dependent variables of [Travel](#travel) are presented using two separate chapters. 

Chapter 2 of [Urban Form](#form) starts from a fundamental question: Do urban form and travel have casual relationship? If not, what is their relationship?
Then the significant influencing factors in literature are systematically introduced.

[Spatial Scales](#scale) is a critical element which can sway the meaning of influencing factors. Careless choosing variable in various scales could even make the results mismatching the initial research questions.

Chapter 3, [the theories of travel behavior](#travel) can be divided into [Traveler Choice][Traveler Choice] and [Human Mobility][Human Mobility] by looking travel as object or subject.
These theories and practice can enrich the understanding of travel variable as response of model.

[Chapter 4][Model Structures] presents several common model structures in existing literature of this field. It demonstrate the different perspectives of the relationship between urban form and travel. Some new trends and methods are also included in this chapter.



