# Analytical and Explanatory Frameworks



It is impossible to design a replicable experiment controlling other factors to identify the effects of density. But it is possible to filter out the unsuitable or irreproducible models.


## Analytical Sturcture

<!-- -   The types of trip variables and the proposed probability distributions -->
<!--     -   Binary: Choose/not to make trip (Bernoulli/Binomial), -->
<!--     -   Polychotomous: modes (Multinomial) and trajectory (Network) -->
<!--     -   Counts: the number of trips (Poisson or NB), -->
<!--     -   Positive continuous: distance and time (Exponential Family: Normal, Log-normal, Power-law, Gamma, Weibull); -->
<!-- -   The unit: Individual or aggregated (household, areal); -->
<!-- -   The temporal scales: Real-time, hourly, Daily, weekly, monthly, yearly/annual, or decade; -->
<!-- -   The spatial scales: Community, city, region, country-wide/national -->
<!-- -   Other taxonomy/division may include -->
<!--     -   traveler roles (returner or explorer); -->
<!--     -   trip purposes; -->
<!--     -   long/short distance/time of trips. -->
<!-- The trip responses are defined in different units, scales, metrics. -->


### By decision-making process

A top-down decision tree starts from a travel demand or purpose. The first choice then reaches a dichotomous node, making a trip or not. The next level of internal nodes is a polychotomous choice, choosing a mode from walking, bicycle, transit, or driving. Each node can further extend to several branches with different routes and departure time, which determine the travel distance and time.

A daily travel could include multiple trips and form a travel chain. The traveler may switch the sequence or adjust the routes to optimize the chain and minimize the travel costs. The daily total travel distance is the summation of every trip distances. The number of trips denotes as trip count. It exists but not so common that driving itself is the travel purpose, especially in daily life.

### By time period

According to the theoretical framework of hierarchical travel behavior introduced by Ben-Akiva and Atherton (1977), travel decision can be divided into three levels:

long-term decisions (e.g. residential location choice)

medium-term decision (car ownership)

short-term decisions (e.g. travel mode choice).

Another fundamental factor that influences travel mode choice behavior is the distance to destination, as would be expected (Munshi, 2016).

## One-step or Multistep

Progressive, iterative, and Habitual

-   H1: One-step mechanism

The traveler makes decision in consideration of all the benefit and cost, including the destination, travel mode, and route at the same moment.

-   H2: Multistep mechanism

The traveler decides to make a trip or not at the first-level node based on the demand, cost, and habitat. The traveler then choose a destination, mode, and route step-by-step from available alternatives.

<!-- the demand or utility of travel is the primary node affecting travel choice.  -->

<!-- The available transportation modes is the secondary nodes which allow the traveler compares and chooses among driving and others. Choosing routes and departure time is in the third level. -->

<!-- The driving distance mainly is decided by the travel demand or utility. Only when the demand is not strong enough or having many alternative destinations, the lower levels' choices could change the driving distance. -->

Which mechanism holds would answer below questions:

Should the zero-VMT and positive-VMT observations be involved in regression analysis?

If the answer is Yes, it implies the two-step (hurdle) models is proper.

Should the no-trip and no-driving observations be confounded in VMT analysis?

The reasons of no trip and no driving might be different.

#### When and How Population density affects travel distance.

Given a driving trip, the distance is decided by the available destinations and their locations.

After choosing the destination, the driving distance could be different among different routes, which affected by the road network.

<!-- If one focuses on auto trips. The tree can be simplified to two levels: driving or not. -->

<!-- From the travel behavior perspective, driving distance locates on a terminal node of a trip decision tree. -->

<!-- The tree shows that the first two level could produce some 'zero' driving distance. Should these cases be included in the studies of driving distance? -->

<!-- This discussion demonstrates a hierarchical relationship among driving distance and other trip variables. -->

<!-- In this way, the transit services located on the second internal nodes. -->

<!-- the travel destination may be determined before the decision making or be selected after the traveler comparing several plans. -->





## Association and Causality

### Association

To estimate the association of VMT response and urban density predictor, the general regression model is:

$$\begin{aligned}
\mathrm{Y}=\mathbf{X}_\mathrm{C}\boldsymbol{\beta}_\mathrm{C}+\mathrm{X_{D}}{\beta}_\mathrm{D}+\mathbf{X}_\mathrm{E}\boldsymbol{\beta}_\mathrm{E}+\boldsymbol{\varepsilon}
\end{aligned}$$

where $\mathrm{Y}$ are the variable of VMT. $\boldsymbol{\beta}$ are the coefficients with respect to travelers' characteristics $\mathbf{X}_\mathrm{C}$, density $\mathrm{X_{D}}$, and other environment covariates $\mathbf{X}_\mathrm{E}$. $\boldsymbol{\varepsilon}$ are the error terms. It could develop different explanatory frameworks, which reflect the cognitive differences on this topic (Figure \@ref(fig:cognitive3)).




### Causal Inference and Self-selection

Essentially, both VMT and density are dependent variable depending by the socioeconomic and techonological development.

However, the urban form remains relatively more stable than individual's travel behavior in each era. A family may be used to driving in Texas and turn to use the subway when they move to New York and vice versa. Given a period, VMT could be affected by density and other factors. It doesn't make sense that VMT will change the density in the short term. Therefore, the relationship of VMT-density can hold in the context of the current stage of urban development and changing travel behaviors.

Early research of automobile trips and urban density can go back sixty years [@mitchellUrbanTraffic1954]. @levinsonEFFECTSDENSITYURBAN1963 suggest that the people who lived in high-density neighborhoods make fewer automobile trips. This paradigm hasn't changed until now. Due to the various data sources, related studies divide into two groups. One group uses aggregated trip and density variables at the city, county, or metropolitan level. At the same time, the other group uses trip data at the individual or household level.

simultaneous equation model

fake

common cause

back-door criterion

The nomological network among travel behavior, socioeconomic, and built environment factors is iterative and cumulative. Causal inference, such as disentangling residential self-selection, requires further evidence and a stronger scheme. This study does not indicate directionality and causality.

Detailed theoretical learning could better answer the question of variable properties and model structures. VMT may be determined by individual's energy and city's opportunity. Then, local density is an irrelevant factor. @ewingTestingNewmanKenworthy2018 comment that the aggregate and disaggregate studies are asking the apples and oranges questions. This study will try to answer what apples and oranges are and what makes the difference.

## Predictors, Mediators or Moderators

(Ding et al., 2017) Based on the fact that travel distance is one of the most important factors influencing travel mode choice, therefore, similar to household car ownership, travel distance also mediates the connection between built environment and mode choice that should be treated as an intermediate variable. Similar framework relates to the study conducted by Van Acker and Witlox (2011).

the influence of the built environment on travel mode choice considering the mediating effects of car ownership, travel distance and travel attitudes. (De Vos et al., 2021)

## Effect Size (Correlations, Coefficients, Elasticities,)

## Generalisability and Reproducibility


