# (PART\*) Part II Data and Methods {-} 

# Data {#data}


Data is the first source of variation. Due to the difficulty of gathering data, it is expected that the data in different studies come from other locations, periods, and groups. Only limited studies use countrywide or worldwide. Partial data may store only pieces of information. Of course, its outcome will only represent the local knowledge rather than the characteristics of the population. Merely adding a specific data source cannot support or against either side. Although people developed more new data-collection techniques and gathered more detailed data in the past years, eliminating the self-report bias is still a challenge. Hence, a nationwide random sampling dataset can mostly address this issue.

Identifying the effects of the built environment on travel behaviors is harder than proving global warming. Scientists can get Antarctic ice core samples but cannot gather everyone's daily travel records, in part because of personal privacy protections, and in part because of limited techniques for gathering these data. Surveys, traffic flow detection, or event data recorder (EDR) can only capture a small piece of the whole picture. Thus, to get a results without loss of generality, wide-range random-sampling data is a critical condition.

### The daily travel data in the U.S.

Nationwide Survey

geographic levels is it statistically valid to use NHTS data

In the 2009 NHTS, estimates are valid down to the state level. However, there are several things to note. First, several states and MPOs purchased add-on samples for their areas, so estimates in those areas may be (but are not necessarily) valid to smaller levels of geography. Second, standard errors (or margins or error in Table Designer) should generally be used, particularly when looking at estimates at geographies smaller than the national level. Third, previous surveys were sampled at even higher levels of geography, meaning samples were not valid down to the state level. For example, in 2001 estimates are valid down to the Census division level, while in 1995 and before, estimates are only valid at the Census region level.

-   Add-on Partner

2001 NHTS, including five states and four MPOs

2009 NHTS interviews were sponsored by the 20 Add-on partners.

With the more robust sample sizes provided in the Add-on areas, States and MPOs are able to perform more in-depth analyses and to drill down to smaller geographic units, such as cities or counties.

2017 NHTS thirteen States or MPOs

<https://www.bts.gov/table-3-2017-nhts-add-partners>

-   Descriptive Statistics

-   Probability Distributions

In the transportation field, there are some valuable studies to identify the distributions of trip variables. Based on some theoretical or empirical studies [^28], scholars prove that trip generating frequency should not choose the linear regression models based on continuous functional forms. A zero-inflated negative binomial model is appropriate to solve the problems of over-dispersion and excess zero. This study implies that the diagnosis of variable distribution may be critical for regression modeling.

[^28]: @hellersteinTheoreticalFoundationCount1993;@jangCountDataModels2005;@bienInflatedMultivariateInteger2011

For continuous variables, it seems like choosing log-normal distribution for trip distance/time is a convention. @puAnalyticRelationshipsTravel2011 choose log-normal as prior assumption because a report called Future Strategic Highway Research Program (F-SHRP) [^29] says "the log-normal distribution is the closest traditional statistical distribution that describes the distribution of travel times." Actually, the new version, SHRP2 says "formal tests (e.g., a Kolmogorov-Smirnov test) could be employed to evaluate the assumption and identify the sensitivity of the results to departures from this assumption." (p. 130)

[^29]: @cambridge2003providing;@kittelson2013evaluating

Meanwhile, @linEstimationEnergyUse2012 validates the daily vehicle miles traveled (DVMT) follows a gamma distribution in the context of PHEV energy analysis. Based on the multidate (7-200 days) data sets from four countries, @plotzDistributionIndividualDaily2017 found Weibull distribution is an overall good two-parameter distribution for daily VKT; while the log-normal estimates are more conservative. The studies on trip distance are still not conclusive. But the attention of three distributions is similar to the survival analysis, which is also called time-to-event analysis [@kleinbaumSurvivalAnalysisSelfLearning2012]. This shows a potential relation with the Distance-Decay, or travel-time-budget theories [@marchettiAnthropologicalInvariantsTravel1994]. Similar to that, @kolblEnergyLawsHuman2003 show a canonical-like energy distribution for short trips by modes, which imply "a law of constant average energy consumption for the physical activity of daily travel". Some studies are not limited in parameter methods. @siminiUniversalModelMobility2012 propose a parameter-free model that predicts patterns of commuting.

-   Historical Trend

This study chooses two informative and available data sources: the National Household Travel Survey (NHTS) [@nhts_2009] and the Smart Location Database (SLD) [@ramsey_smart_2014] as the data source.

NHTS [^30] is a nation-wide travel survey on travel and transportation patterns in the United States. NHTS includes some essential trip variables: number of trips, purpose, modes, VMT, etc. This is the first advantage over the local data source.

[^30]: NHTS conducted in 2001, 2009, and 2017 by the Federal Highway Administration (FHWA). The prior Nationwide Personal Transportation Surveys (NPTS) conducted in 1969, 1977, 1983, 1990, and 1995

NHTS is a well-designed survey. Some deliberate sampling methods make NHTS data representing the population-level travel characteristics. Although it is not as detailed as the GPS data, as large as the social media data, the second advantage of NHTS is it satisfies the fundamental requirement of statistic inference: random sampling.

The new NHTS (2009 and 2017) "weights its person data based on control totals found in the American Community Survey (ACS)." [^31] This provides an opportunity of joining travel data to other demographic, employment, and built environment data. SLD also covers the entire US. The Environmental Protection Agency (EPA) conducted SLD for measuring location efficiency and the built environment [^32]. SLD synthesized many data sources in around 2010 [^33] [^34] [^35] [^36] [^37] [^38] [^39] [^40]. SLD have more than 90 variables including *'density of development, diversity of land use, street network design, and accessibility to destinations.'* 2009 NHTS and SLD have the same period and can join together by geographic locations. The initial data dimension is 150,145 observations by 192 variables. Hence, the joint datasets contain both trip and built environment information to fit VMT-density models.

[^31]: <https://www.census.gov/programs-surveys/decennial-census/about/census-acs.html>

[^32]: <https://www.epa.gov/smartgrowth/smart-location-mapping>

[^33]: 2010 Census (<http://www.census.gov/2010census/data/>)

[^34]: 2010 ACS

[^35]: LEHD Origin-Destination Employment Statistics (LODES)

[^36]: InfoUSA (<http://www.infousa.com/>)

[^37]: NAVTEQ (<http://www.navteq.com/products_data.htm>)

[^38]: PAD-US (<http://gapanalysis.usgs.gov/padus/>)

[^39]: TOD Database (<http://toddata.cnt.org/>)

[^40]: GTFS (<https://developers.google.com/transit/gtfs/>)

The last advantage is this dataset has almost reached the finest resolution for travel v.s built environment analysis. As found in literature, a parallel study requires the data includes multi-scale information.

NHTS is conducted at four units: trip, person, vehicle, and household. While SLD is collected at the Census block group (CBG) level. The attributes can be synthesized at block, tract, county, and city scales by geographic identifiers (Table \@ref(tab:geoid)). [^41]

[^41]: <https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html>

```{=tex}
\begin{table}[h]
\begin{tabular}{|c|l|r|}\hline
Area Type & GEOID & Geographic Area \\\hline
State     &  41   & Oregon \\
County    & 41051 & Multnomah County, OR \\
County Subdivision & 4105192520 & Portland West CCD, Multnomah County, OR \\
Places    & 4159000 & Portland city, OR \\
Tract     & 410510056 & Census Tract 56, Multnomah County, OR \\
Block Group & 410510056002    & Block Group 2, Census Tract 56, Multnomah County, OR \\
Block       & 410510056002014 & Block 2014, Census Tract 56, Multnomah County, OR \\\hline
\multicolumn{3}{|c|}{Other Census Geographic Entities} \\\hline
CSA   & 440      & Portland-Vancouver-Salem, OR-WA  \\
CMSA  & 6442     & Portland--Salem, OR--WA \\
CBSA  & 38900      & Portland-Vancouver-Hillsboro, OR-WA \\
UACE  & 71317      & Portland, OR--WA \\
PUMA   & 4101314 & Portland City (Northwest \& Southwest)   \\\hline
\end{tabular}
\centering
\caption{\label{tab:geoid}GEOID Structure for Geographic Areas}
\end{table}
```
At least two scales need to be aggregated: One is Core Based Statistical Area (CBSA) [^42]. Another important scale is Urban Areas (including 486 Urbanized Areas and 3,087 Urban Clusters in 2010) [^43] It allows a cities-to-cities, metro-to-metro comparison with an uniform data source (Figure \@ref(fig:diagram3)).

[^42]: there are384 metropolitan statistical areas and 543 micropolitan statistical areas as of 2020. The 2010 standards provide that each CBSA must contain at least one urban area of 10,000 or more population. Each metropolitan statistical area must have at least one urbanized area of 50,000 or more inhabitants. Each micropolitan statistical area must have at least one urban cluster of at least 10,000 but less than 50,000 population.

[^43]: 2010 Census Urban and Rural Classification and Urban Area Criteria Urbanized Areas (UAs) of 50,000 or more people; Urban Clusters (UCs) of at least 2,500 and less than 50,000 people. (<https://www.census.gov/programs-surveys/geography/guidance/geo-areas/urban-rural/2010-urban-rural.html>)

```{r diagram3,eval=T,fig.cap='The aggregate procedure',fig.dim = c(9,2.5),fig.pos="H"}
grViz("
digraph G {
graph[fontname = 'helvetica',  nodesep=0.4, overlap='prism1000']
rankdir = LR
node [fontname = 'helvetica', style = filled, fillcolor = WhiteSmoke, height = 0.75, width = 1, fontcolor = black];

node[fillcolor = PapayaWhip, shape = circle]
# node [shape=none, width=0, height=0, label='']

    subgraph{
    label = '';
    style=dashed;	color= '#625a5a'; fontname = 'helvetica-bold';
		node [shape=plain, style=filled, color=black, fillcolor = WhiteSmoke]; # '#91cf60'
    rank = same
    t[label = 'Trip']; t1[label = 'Person']
    s0[label = 'Population size']; s1[label = 'Area size']; s2[label = '@@3']
    t ->t1[label='@@4',splines = none]
    s0 -> s1 -> s2[style=invis]
    }

    subgraph cluster_H {
    label = 'NHTS + SLD';
    style=dashed;	color= '#625a5a'; fontname = 'helvetica-bold';
		node [shape=plain, style=filled, color=black, fillcolor = WhiteSmoke]; # '#91cf60'
    t0[label = '0 Trip']; v0[label = '0 VMT']
    node [shape = cylinder, fillcolor = WhiteSmoke]
    h[label = 'Household']
    be[label = 'Built Environment']
    s0 -> be; s1 -> be; s2 -> be
    t -> h[label='@@4']; t1 -> h[label='@@4',splines = none]
    t -> t0[style=dashed]; t -> v0[style=dashed]
    # h -> be [dir=none,style=dashed,splines = none]
    }

    subgraph cluster_B {
    label = 'Block Level';
    style=dashed;	color= '#625a5a'; fontname = 'helvetica-bold';
		node [shape=box3d, style=filled, color=black, fillcolor = WhiteSmoke];
    Vb[label = '@@1']; D1b[label = '@@2']; Db[label = '@@3']
    # Vb0[label = 'VMT_b0']; # B0[style=invis]
    # D2[label = 'Diversity']# D3[label = 'Design'] # D4[label = 'Transit']# D5[label = 'Destination']
    }

    subgraph cluster_T {
    label = 'Tract Level';
    style=dashed;	color= '#625a5a'; fontname = 'helvetica-bold';
    rank = same
    node [shape = tab, fillcolor = cornsilk]
    Vt[label = '@@1']; D1t[label = '@@2']; Dt[label = '@@3']
    # Vt0[label = 'VMT_t0']    # T[style=invis]
    }

    subgraph cluster_C {
    label = 'County Level';
    style=dashed;	color= '#625a5a'; fontname = 'helvetica-bold';
    node [shape = folder, fillcolor = Beige]
    Vc[label = '@@1']; D1c[label = '@@2']; Dc[label = '@@3']
    # Vc0[label = 'VMT_c0'] # C[style=invis]
    }

    subgraph cluster_M {
    label = 'Metro Level';
    style=dashed;	color= '#625a5a'; fontname = 'helvetica-bold';
    node [shape = box, fillcolor = PapayaWhip]
    Vm[label = '@@1']; D1m[label = '@@2']; Dm[label = '@@3']
    # Vm0[label = 'VMT_m0'] # M[style=invis]
    }

h -> Vb  -> Vt -> Vc -> Vm[splines = none,label='&Sigma;/n']
t0 -> Vb[style=dashed,splines = none]; v0 -> Vb[style=dashed,splines = none]
be -> D1b -> D1t -> D1c -> D1m[splines = none]
be -> Db -> Dt -> Dc -> Dm
# t2 -> {dist Model} -> f4_2 [dir=back,style=dashed,splines = none]
}

[1]: paste0('VMT')
[2]: paste0('Density')
[3]: paste0('... ...')
[4]: paste0('&Sigma;')

")
```

Other data sources such as Call Detail Records (CDR), GPS, ICT, Point of Interest (POI), etc., can be combined with NHTS and SLD to enrich the information as long as one data contain the same index variable. For example, Point of Interest may represent the number of opportunities of place or utility of place. Although some data have high resolution and plenty of information, the geographic restriction and self-report bias should not be neglected.

However, there are 57 5-D variables in SLD. The variables inside each D group are highly correlated. Based on previous research, this pilot study chooses only one variable from each D group.[^44]

[^44]: D1B: Gross population density (people/acre) on unprotected land; D2A_WRKEMP: Household Workers per Job, by CBG; D3a: Total road network density; D4b050: Proportion of CBG employment within ½ mile of fixed-guideway transit stop; D5ar: Jobs within 45 minutes auto travel time, time decay (network travel time) weighted.

#### Trips, Vehicle, Personal, Household

Aggregate data is more accessible and more convenient to combine with other data sources. For example, @ewingTestingNewmanKenworthy2018 use the average per capita VMT of all urbanized areas across the U.S. from FHWA's Highway Statistics. They joined the 2010 census tracts to FHWA's 157 urbanized areas with populations of two hundred thousand or more.

For disaggregate studies, collecting complete personal travel records and the built environment information is difficult. A common way is to get travel survey data from the local department of transportation and combine it with census data and GIS data. Many scholars start their relevant research from neighborhoods data, then extend the scope to the whole city or metropolitan area. Among the selected nine VMT-density studies in @ewingTravelBuiltEnvironment2010, eight use single city/metro data[^45]. Only one nationwide study using NPTS data [@schimekHouseholdMotorVehicle1996] finds logarithm of household VMT has a non-significant elasticity (-0.07). Some studies begin to cover multi-region data [@zhangHowBuiltEnvironment2012]. @ewingVaryingInfluencesBuilt2015 accumulated a travel and built environmental dataset from 23 metropolitan regions in US [^46]. They find that all of the 11 D-variables have statistically significant effects on VMT.

[^45]: @ewing2009measuring: Portland, elas=0.00; @frankMultipleImpactsBuilt2005 Misquote,Seattle , elas=0.00; @greenwald2009sacsim Sacramento, elas=-0.07 (Non-significant, Unpublished); @mariakockelmanTravelBehaviorFunction1997,Bay Area, elas=0.00; @kuzmyak2009estimating Los Angeles, elas=-0.04 (Unpublished); @kuzmyak2009estimates Phoenix,elas=0.00 (Unpublished); @zegrasBuiltEnvironmentMotor2010 Santiago de Chile, elas=-0.04; @zhouSelfSelectionHomeChoice2008 Austin, elas=-0.12, no-log, $R^2$=0.097

[^46]: 81,056 households and 815,204 people

Since 1969, there is a person/household-level data on travel and transportation patterns in the United States, called the National Personal/Household Travel Survey (NPTS/NHTS). NHTS data include population density of census tract and gasoline-equivalent gallons consumed per year. Some studies use NHTS data to modeling the automotive CO$_2$ emissions [@kimImpactResidentialDensity2013; @perumalContextualDensityUS2017]. But this dataset doesn't contain enough built environment information and cannot support a full VMT-5Ds variable studies. Some studies add psychological factors such as role preferences, motivations, and expectations in choices to the models. @hongHowBuiltenvironmentFactors2014 use eight attitudinal questions in the 2006 Household Activity Survey and improve the models' $R^2$ over 0.7.

-   Sampling methods

### Socio-Demographic Data

### Built-Environment Data

### New Data Source

There are more and more transportation studies using GPS, ICT, trajectory, Point of Interest (POI) and social media data. @liuPointofInterestDemandModeling2017 use Point-of-Interest (POI) demand modeling to analyze human mobility patterns. @damianiLocationRelevanceDiversity2020 use trajectory summarization technique for the extraction of the locations of interest high-quality information. Using image recognition techniques, satellite imagery and Street View data provide unprecedented built environment information. The advantage of these new data sources is the high resolution and detailed information. Combining two types of data sources together has tremendous potential to answer VMT-built environment questions. However, the enormous amount of emerging data is also a huge challenge. The analysis methods of abstracting out generic information lags behind the data collection. How to eliminate the sample bias in new data sources is another unfinished work.
