

# Summary {#summary}

Part II starts from the first question in modeling, what type of model we should choose?
Then the following question is, do this method is correct?
The last question would be, how can we do better?
Recent literature usually focus on the third question.
But for any research, the first two questions are not obvious or self-evidence.
Thus, the this paper makes efforts to review some fundamental knowledge.

For the first question, existing theories have given some hints for sorting the travel data and models according to their properties.
But in literature, there are some still contradictory cases need further test and comparison (e.g. ordinary linear models with log-transform on count data v.s. count data models).
Each method has the suitable application and limitations. For example, PCA become less used in the last three years because it is hard to interpret.

Several common issues are presented to remind the second questions.
Derivation and test are two ways of proving a statistical method. In the literature, we can only see the author's choices of data and methods. Without replicating the models, it is hard to assess the methods.
The real world have no perfect data. Although some diagnosis and validation methods can aid us to find some problems, the results would not tell us what should we do automatically. The only way is to try many data, methods, and check the results repeatedly.

Spatial effects are heeded in recent studies. For heterogeneous issues, GWR and aggregation represent two distinct solutions.
GWR tries to capture the local dynamic among the spatial data and require intensive computation.
The aggregated methods try to eliminate heterogeneity. As the sample sizes inside the aggregating areas increasing, the variance of estimated coefficients will decrease. 
"Ecological fallacy" sounds like a mistake. Small scale could also distract the researchers by unimportant details.
Suitable aggregated data and models structure should match the research question.

Capturing the nonlinear feathers is also popular in recent studies. 
From the perspective of policy implementation, public may only concern about some effective ranges of variables.
For example in rural area or CBD, population density would not be a useful tool for intervention.
Threshold effects or synergistic effects are also interesting because they can tell planner and policy makers how to select effective combination from the toolbox.
There always are new methods being developed. 
This paper gives a brief on some advanced methods such as machine learning. These methods provide additional tools for examining the results and would not replace traditional method at present.

<!-- Though this paper, a gain is that now I can identify what the category one method belongs to.  -->
<!-- If some methods such as machine learning is required, I can make further study on this topic.  -->

<!-- Critically discussing the statistical methods in literature is a huge challenge. -->
<!-- Most of the time, I try to understand what the methods are and mainly focus on the classic approaches. -->
<!-- I often doubt whether my commons is correct or misunderstand the author's meaning or the method itself. -->
<!-- It is necessary to read these cited articles third time and more. -->

-   Meta-Analysis in travel-urban form studies

The meta-analysis in travel-urban form studies faces more exacting challenges.
The same on many social studies, travel-urban form studies use observation design.
They cannot satisfy the requirement of randomized controlled trials (RCT).
The urban environment factors have many unknown and complex influences on travel behavior.
They are not controllable as in laboratory.
All the traveler lives in many kinds of urban environment.
There is no control group for measuring the between-group mean difference.
Most of travel survey only capture a moment of travel pattern.
There is no repeat measurement for evaluating the random error.
These shortfalls also make the relevant studies are highly heterogeneous.
If the scope of studies is wide, the validity of meta-analysis becomes problematic.
If the selection criteria is rigorous, there might be less than 10 studies on a topic.

Although meta-analysis in travel-urban form studies is not as reliable as the studies of RCT.
Scholars still put effort into this approach.
Because a generalized conclusion could have substential influence on policy making and social attitudes.

<!-- `r if (knitr:::is_html_output()) ' -->

# References {-}

